# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
 - name: spnName
   value: 'pipelines-runner'
 - name: blueprintName
   value: 101-Boilerplate
 - name: subscriptionId
   value: 'e93d3ee6-fac1-412f-92d6-bfb379e81af2'

steps:

- task: CreateBlueprint@1
  displayName: 'Push Yum-ISO-Foundations blueprint to Azure'
  inputs:
    azureSubscription: '$(spnName)' # this is the service connection
    BlueprintName: '$(blueprintName)'
    BlueprintPath: '.\samples\$(blueprintName)'
    PublishBlueprint: true

- task: AssignBlueprint@1
  displayName: 'Assign Yum-ISO-Foundations blueprint to test environment'
  inputs:
    azureSubscription: '$(spnName)'
    AssignmentName: 'pla-$(blueprintName)' # pla == PipeLinesAssignment
    BlueprintName: '$(blueprintName)'
    ParametersFile: '.\samples\$(blueprintName)\assign.json'
    SubscriptionID: '$(subscriptionId)'
    Wait: true # waits for assignment to succeed or fail
    # version not specified because it defaults to latest published, but could include it

# clean subscription before next test
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'pipelines-runner'
    ScriptType: 'FilePath'
    ScriptPath: '.\clean-subscription.ps1'
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'
